#!/usr/bin/env python3
"""
Choir V2.0 Factory Preset Generator
Generates 50 comprehensive presets showcasing all capabilities
"""

import json
import os
from datetime import datetime

def create_preset(name, description, language, synthesis_method, lyrics,
                 num_voices=8, formant_mix=80, subharmonic_mix=20,
                 stereo_width=75, vibrato_rate=6.0, vibrato_depth=30.0,
                 reverb_mix=25, reverb_size=50, attack=50, release=200,
                 pitch_variation=10, timing_variation=5, formant_variation=15,
                 breathiness=10, warmth=20, brightness=50, tags=None):
    """Create a preset dictionary"""

    preset = {
        "metadata": {
            "name": name,
            "author": "Bret Bouchard",
            "description": description,
            "version": "2.0.0",
            "category": "Factory",
            "tags": tags or [],
            "created_date": datetime.now().isoformat(),
            "modified_date": datetime.now().isoformat(),
            "plugin_version": "2.0.0"
        },
        "parameters": {
            "num_voices": num_voices,
            "master_gain": -3.0,
            "language": language,
            "lyrics": lyrics,
            "synthesis_method": synthesis_method,
            "formant_mix": formant_mix,
            "subharmonic_mix": subharmonic_mix,
            "stereo_width": stereo_width,
            "vibrato_rate": vibrato_rate,
            "vibrato_depth": vibrato_depth,
            "reverb_mix": reverb_mix,
            "reverb_size": reverb_size,
            "attack_time": attack,
            "release_time": release,
            "enable_anti_aliasing": True,
            "enable_spectral_enhancement": True,
            "oversampling_factor": 1.0,
            "pitch_variation": pitch_variation,
            "timing_variation": timing_variation,
            "formant_variation": formant_variation,
            "breathiness": breathiness,
            "warmth": warmth,
            "brightness": brightness
        },
        "is_factory": True,
        "is_read_only": True
    }
    return preset

def save_preset(preset, directory):
    """Save preset to JSON file"""
    filename = f"{preset['metadata']['name'].replace(' ', '_').replace('/', '_')}.choirv2"
    filepath = os.path.join(directory, filename)

    with open(filepath, 'w') as f:
        json.dump(preset, f, indent=2)

    print(f"✓ Created: {preset['metadata']['name']}")

# ============================================================================
# SCHILLINGER SONGS (5 presets) - Rhythmic & Mathematical Patterns
# ============================================================================

schillinger_presets = [
    create_preset(
        "Schillinger 1: Square Rhythm",
        "Mathematical rhythmic pattern using square wave symmetry",
        "english",
        "formant",
        "ah oh ah oh ee oh ah oh",
        num_voices=4,
        formant_mix=90,
        subharmonic_mix=10,
        stereo_width=60,
        vibrato_rate=5.0,
        vibrato_depth=20,
        reverb_mix=15,
        reverb_size=30,
        attack=30,
        release=150,
        breathiness=5,
        warmth=15,
        brightness=60,
        tags=["schillinger", "rhythmic", "mathematical", "english"]
    ),
    create_preset(
        "Schillinger 2: Rotational Symmetry",
        "Voice rotation with phase-shifted entrances",
        "latin",
        "diphone",
        "ah-eh ee-oh oh-oo oo-ah",
        num_voices=6,
        formant_mix=85,
        subharmonic_mix=15,
        stereo_width=80,
        vibrato_rate=6.5,
        vibrato_depth=25,
        reverb_mix=20,
        reverb_size=40,
        attack=40,
        release=180,
        pitch_variation=15,
        timing_variation=8,
        warmth=25,
        brightness=55,
        tags=["schillinger", "rotational", "latin", "diphone"]
    ),
    create_preset(
        "Schillinger 3: Permutation Generator",
        "All permutations of 4 vowels, 24 voices",
        "english",
        "formant",
        "ah ee ih oh oo",
        num_voices=24,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=100,
        vibrato_rate=5.5,
        vibrato_depth=15,
        reverb_mix=30,
        reverb_size=60,
        attack=25,
        release=200,
        pitch_variation=5,
        timing_variation=3,
        formant_variation=10,
        warmth=30,
        brightness=70,
        tags=["schillinger", "permutation", "large-ensemble", "english"]
    ),
    create_preset(
        "Schillinger 4: Harmonic Symmetry",
        "Symmetric harmonic intervals, perfect fifths",
        "klingon",
        "subharmonic",
        "ghgh ghgh vadh vadh",
        num_voices=8,
        formant_mix=50,
        subharmonic_mix=50,
        stereo_width=70,
        vibrato_rate=4.0,
        vibrato_depth=35,
        reverb_mix=25,
        reverb_size=50,
        attack=60,
        release=250,
        pitch_variation=8,
        timing_variation=5,
        warmth=35,
        brightness=40,
        tags=["schillinger", "harmonic", "subharmonic", "klingon"]
    ),
    create_preset(
        "Schillinger 5: Resultant Rhythm",
        "Resultant rhythm from 3:2 polyrhythm",
        "throat_singing",
        "subharmonic",
        "oh oh oh oh oh",
        num_voices=12,
        formant_mix=30,
        subharmonic_mix=70,
        stereo_width=90,
        vibrato_rate=3.0,
        vibrato_depth=40,
        reverb_mix=35,
        reverb_size=65,
        attack=80,
        release=300,
        pitch_variation=5,
        timing_variation=2,
        formant_variation=20,
        breathiness=15,
        warmth=45,
        brightness=35,
        tags=["schillinger", "polyrhythm", "throat-singing", "subharmonic"]
    ),
]

# ============================================================================
# CLASSICAL MUSIC (5 presets) - Historical Choral Works
# ============================================================================

classical_presets = [
    create_preset(
        "Classical 1: Gregorian Chant",
        "Traditional monophonic Gregorian chant",
        "latin",
        "formant",
        "ah-eh-ee-oh-oo",
        num_voices=12,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=50,
        vibrato_rate=4.0,
        vibrato_depth=10,
        reverb_mix=40,
        reverb_size=80,
        attack=100,
        release=400,
        pitch_variation=5,
        timing_variation=3,
        formant_variation=5,
        breathiness=20,
        warmth=50,
        brightness=30,
        tags=["classical", "gregorian", "chant", "latin", "reverb"]
    ),
    create_preset(
        "Classical 2: Bach Chorale",
        "J.S. Bach four-part harmony style",
        "english",
        "diphone",
        "ah-eh ee-oh oh-oo oo-ah",
        num_voices=4,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=60,
        vibrato_rate=5.5,
        vibrato_depth=22,
        reverb_mix=25,
        reverb_size=45,
        attack=45,
        release=200,
        pitch_variation=8,
        timing_variation=4,
        warmth=35,
        brightness=50,
        tags=["classical", "bach", "chorale", "english", "harmony"]
    ),
    create_preset(
        "Classical 3: Renaissance Polyphony",
        "Palestrina-style 6-voice polyphony",
        "latin",
        "diphone",
        "ah-eh ee-oh oo-ah eh-ee",
        num_voices=6,
        formant_mix=90,
        subharmonic_mix=10,
        stereo_width=70,
        vibrato_rate=6.0,
        vibrato_depth=18,
        reverb_mix=30,
        reverb_size=55,
        attack=50,
        release=220,
        pitch_variation=12,
        timing_variation=6,
        formant_variation=8,
        breathiness=12,
        warmth=40,
        brightness=45,
        tags=["classical", "renaissance", "polyphony", "latin", "palestrina"]
    ),
    create_preset(
        "Classical 4: Romantic Era Choir",
        "Large romantic orchestra choir, Brahms-style",
        "english",
        "formant",
        "oh oo ah eh ee",
        num_voices=32,
        formant_mix=85,
        subharmonic_mix=15,
        stereo_width=90,
        vibrato_rate=6.5,
        vibrato_depth=28,
        reverb_mix=35,
        reverb_size=70,
        attack=60,
        release=300,
        pitch_variation=15,
        timing_variation=7,
        formant_variation=12,
        breathiness=18,
        warmth=55,
        brightness=55,
        tags=["classical", "romantic", "large-ensemble", "brahms", "english"]
    ),
    create_preset(
        "Classical 5: Orthodox Chant",
        "Byzantine orthodox chanting with ison",
        "klingon",
        "subharmonic",
        "ghgh vadh ghgh vadh",
        num_voices=8,
        formant_mix=40,
        subharmonic_mix=60,
        stereo_width=40,
        vibrato_rate=3.5,
        vibrato_depth=25,
        reverb_mix=45,
        reverb_size=90,
        attack=120,
        release=500,
        pitch_variation=3,
        timing_variation=2,
        breathiness=8,
        warmth=60,
        brightness=25,
        tags=["classical", "orthodox", "byzantine", "klingon", "ison"]
    ),
]

# ============================================================================
# ORIGINAL COMPOSITIONS (15 presets) - Creative Showcase
# ============================================================================

original_presets = [
    create_preset(
        "Original 1: Ethereal Dreamscape",
        "Ambient soundscape with slow formant transitions",
        "english",
        "formant",
        "ah oo ee oh",
        num_voices=16,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=100,
        vibrato_rate=2.0,
        vibrato_depth=15,
        reverb_mix=60,
        reverb_size=100,
        attack=200,
        release=800,
        pitch_variation=20,
        timing_variation=10,
        formant_variation=25,
        breathiness=25,
        warmth=70,
        brightness=40,
        tags=["original", "ambient", "ethereal", "slow", "english"]
    ),
    create_preset(
        "Original 2: Alien Chorus",
        "Otherworldly harmonies using Klingon",
        "klingon",
        "diphone",
        "ghgh vadh qlIj ghgh vadh",
        num_voices=12,
        formant_mix=70,
        subharmonic_mix=30,
        stereo_width=85,
        vibrato_rate=7.5,
        vibrato_depth=35,
        reverb_mix=40,
        reverb_size=60,
        attack=40,
        release=250,
        pitch_variation=18,
        timing_variation=8,
        formant_variation=20,
        breathiness=15,
        warmth=30,
        brightness=70,
        tags=["original", "alien", "klingon", "sci-fi", "harmonies"]
    ),
    create_preset(
        "Original 3: Throat Singing Ensemble",
        "Tuvan throat singing with subharmonics",
        "throat_singing",
        "subharmonic",
        "oh oh oh oh",
        num_voices=8,
        formant_mix=20,
        subharmonic_mix=80,
        stereo_width=75,
        vibrato_rate=3.0,
        vibrato_depth=45,
        reverb_mix=20,
        reverb_size=40,
        attack=100,
        release=400,
        pitch_variation=5,
        timing_variation=3,
        formant_variation=15,
        breathiness=10,
        warmth=50,
        brightness=30,
        tags=["original", "throat-singing", "tuvan", "subharmonic", "ensemble"]
    ),
    create_preset(
        "Original 4: Cathedral Echoes",
        "Massive reverberant church choir",
        "latin",
        "formant",
        "ah-eh-ee-oh-oo",
        num_voices=40,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=95,
        vibrato_rate=5.0,
        vibrato_depth=20,
        reverb_mix=70,
        reverb_size=100,
        attack=80,
        release=600,
        pitch_variation=12,
        timing_variation=6,
        formant_variation=10,
        breathiness=15,
        warmth=65,
        brightness=45,
        tags=["original", "cathedral", "large-ensemble", "reverb", "latin"]
    ),
    create_preset(
        "Original 5: Synthetic Voices",
        "Pure formant synthesis, minimal natural characteristics",
        "english",
        "formant",
        "ah ee ih oh oo",
        num_voices=6,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=50,
        vibrato_rate=0.0,
        vibrato_depth=0,
        reverb_mix=10,
        reverb_size=20,
        attack=10,
        release=100,
        pitch_variation=0,
        timing_variation=0,
        formant_variation=5,
        breathiness=0,
        warmth=10,
        brightness=80,
        tags=["original", "synthetic", "electronic", "formant", "clean"]
    ),
    create_preset(
        "Original 6: whispers in the Dark",
        "Intimate breathy close-miked whispering",
        "english",
        "diphone",
        "ah-eh ee-oh oh-oo",
        num_voices=4,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=40,
        vibrato_rate=4.0,
        vibrato_depth=12,
        reverb_mix=5,
        reverb_size=15,
        attack=30,
        release=150,
        pitch_variation=5,
        timing_variation=3,
        formant_variation=8,
        breathiness=50,
        warmth=40,
        brightness=35,
        tags=["original", "whisper", "intimate", "breathy", "english"]
    ),
    create_preset(
        "Original 7: Cosmic Resonance",
        "Space-themed ambient with Klingon and subharmonics",
        "klingon",
        "subharmonic",
        "vadh ghgh qlIj",
        num_voices=16,
        formant_mix=30,
        subharmonic_mix=70,
        stereo_width=100,
        vibrato_rate=2.5,
        vibrato_depth=30,
        reverb_mix=55,
        reverb_size=95,
        attack=150,
        release=700,
        pitch_variation=25,
        timing_variation=12,
        formant_variation=18,
        breathiness=20,
        warmth=55,
        brightness=50,
        tags=["original", "cosmic", "space", "klingon", "ambient"]
    ),
    create_preset(
        "Original 8: Medieval Tavern",
        "Rustic folk choir from medieval times",
        "english",
        "diphone",
        "ah oh oo ah oh",
        num_voices=8,
        formant_mix=90,
        subharmonic_mix=10,
        stereo_width=55,
        vibrato_rate=5.0,
        vibrato_depth=25,
        reverb_mix=15,
        reverb_size=30,
        attack=35,
        release=180,
        pitch_variation=10,
        timing_variation=5,
        breathiness=12,
        warmth=55,
        brightness=40,
        tags=["original", "medieval", "folk", "rustic", "english"]
    ),
    create_preset(
        "Original 9: Quantum Choir",
        "Experimental microtonal harmonies",
        "klingon",
        "formant",
        "ghgh vadh qlIj",
        num_voices=24,
        formant_mix=80,
        subharmonic_mix=20,
        stereo_width=90,
        vibrato_rate=8.0,
        vibrato_depth=40,
        reverb_mix=35,
        reverb_size=50,
        attack=25,
        release=200,
        pitch_variation=30,
        timing_variation=15,
        formant_variation=30,
        breathiness=10,
        warmth=35,
        brightness=75,
        tags=["original", "quantum", "experimental", "microtonal", "klingon"]
    ),
    create_preset(
        "Original 10: Ancient Spirits",
        "Primordial vocal sounds from throat singing",
        "throat_singing",
        "subharmonic",
        "oh oh oh",
        num_voices=6,
        formant_mix=10,
        subharmonic_mix=90,
        stereo_width=65,
        vibrato_rate=2.0,
        vibrato_depth=50,
        reverb_mix=30,
        reverb_size=70,
        attack=180,
        release=500,
        pitch_variation=8,
        timing_variation=4,
        formant_variation=12,
        breathiness=5,
        warmth=70,
        brightness=20,
        tags=["original", "ancient", "primordial", "throat-singing", "spirits"]
    ),
    create_preset(
        "Original 11: Digital Dreams",
        "Glitchy electronic vocal synthesis",
        "english",
        "formant",
        "ah ee ih oh oo",
        num_voices=8,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=70,
        vibrato_rate=10.0,
        vibrato_depth=15,
        reverb_mix=20,
        reverb_size=35,
        attack=5,
        release=80,
        pitch_variation=2,
        timing_variation=1,
        formant_variation=3,
        breathiness=5,
        warmth=15,
        brightness=90,
        tags=["original", "digital", "electronic", "glitch", "synth"]
    ),
    create_preset(
        "Original 12: Norse Shield Chant",
        "Viking-era shield wall chanting",
        "klingon",
        "subharmonic",
        "ghgh ghgh vadh vadh",
        num_voices=20,
        formant_mix=40,
        subharmonic_mix=60,
        stereo_width=80,
        vibrato_rate=4.5,
        vibrato_depth=35,
        reverb_mix=25,
        reverb_size=45,
        attack=50,
        release=250,
        pitch_variation=8,
        timing_variation=5,
        formant_variation=15,
        breathiness=15,
        warmth=60,
        brightness=35,
        tags=["original", "norse", "viking", "chant", "klingon"]
    ),
    create_preset(
        "Original 13: Celestial Harmony",
        "Angelic choir with extended reverb",
        "latin",
        "diphone",
        "ah-eh ee-oh oh-oo",
        num_voices=16,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=85,
        vibrato_rate=5.5,
        vibrato_depth=22,
        reverb_mix=65,
        reverb_size=100,
        attack=90,
        release=700,
        pitch_variation=10,
        timing_variation=5,
        formant_variation=8,
        breathiness=18,
        warmth=60,
        brightness=55,
        tags=["original", "celestial", "angelic", "reverb", "latin"]
    ),
    create_preset(
        "Original 14: Underground Chamber",
        "Cave-like environment with tight reflections",
        "english",
        "formant",
        "ah oh oo",
        num_voices=6,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=45,
        vibrato_rate=4.0,
        vibrato_depth=18,
        reverb_mix=30,
        reverb_size=25,
        attack=40,
        release=120,
        pitch_variation=6,
        timing_variation=4,
        breathiness=8,
        warmth=45,
        brightness=50,
        tags=["original", "cave", "underground", "intimate", "english"]
    ),
    create_preset(
        "Original 15: Infinite Voices",
        "Massive ensemble with 60 voices",
        "latin",
        "formant",
        "ah-eh-ee-oh-oo",
        num_voices=60,
        formant_mix=90,
        subharmonic_mix=10,
        stereo_width=100,
        vibrato_rate=6.0,
        vibrato_depth=25,
        reverb_mix=40,
        reverb_size=75,
        attack=70,
        release=400,
        pitch_variation=15,
        timing_variation=8,
        formant_variation=12,
        breathiness=12,
        warmth=50,
        brightness=60,
        tags=["original", "massive", "infinite", "large-ensemble", "latin"]
    ),
]

# ============================================================================
# LANGUAGE SHOWCASE (25 presets) - At least 1 per fake language, 3 per real
# ============================================================================

language_presets = [
    # ENGLISH (3 presets) - Real language
    create_preset(
        "English 1: Pop Choir",
        "Modern pop backing vocals",
        "english",
        "diphone",
        "ah-eh ee-oh oh-oo",
        num_voices=8,
        formant_mix=90,
        subharmonic_mix=10,
        stereo_width=70,
        vibrato_rate=6.0,
        vibrato_depth=25,
        reverb_mix=20,
        reverb_size=40,
        attack=30,
        release=180,
        breathiness=10,
        warmth=35,
        brightness=60,
        tags=["english", "pop", "modern", "backing-vocals"]
    ),
    create_preset(
        "English 2: Gospel Choir",
        "Traditional gospel choir with soul",
        "english",
        "formant",
        "oh ah ee oh oo ah",
        num_voices=24,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=85,
        vibrato_rate=7.0,
        vibrato_depth=35,
        reverb_mix=30,
        reverb_size=50,
        attack=50,
        release=250,
        pitch_variation=12,
        timing_variation=6,
        breathiness=15,
        warmth=55,
        brightness=55,
        tags=["english", "gospel", "soul", "choir", "large-ensemble"]
    ),
    create_preset(
        "English 3: Barbershop Quartet",
        "Close-harmony barbershop style",
        "english",
        "diphone",
        "ah-eh ee-oh",
        num_voices=4,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=60,
        vibrato_rate=6.5,
        vibrato_depth=28,
        reverb_mix=10,
        reverb_size=25,
        attack=25,
        release=150,
        pitch_variation=5,
        timing_variation=3,
        breathiness=8,
        warmth=45,
        brightness=50,
        tags=["english", "barbershop", "quartet", "harmony"]
    ),

    # LATIN (3 presets) - Real language
    create_preset(
        "Latin 1: Requiem Mass",
        "Traditional requiem mass choir",
        "latin",
        "formant",
        "ah-eh-ee-oh-oo",
        num_voices=32,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=80,
        vibrato_rate=5.0,
        vibrato_depth=20,
        reverb_mix=45,
        reverb_size=85,
        attack=80,
        release=450,
        breathiness=12,
        warmth=60,
        brightness=45,
        tags=["latin", "requiem", "mass", "classical", "large-ensemble"]
    ),
    create_preset(
        "Latin 2: Motet Polyphony",
        "Renaissance motet style",
        "latin",
        "diphone",
        "ah-eh ee-oh oh-oo",
        num_voices=8,
        formant_mix=92,
        subharmonic_mix=8,
        stereo_width=65,
        vibrato_rate=5.5,
        vibrato_depth=18,
        reverb_mix=28,
        reverb_size=50,
        attack=45,
        release=200,
        pitch_variation=10,
        timing_variation=5,
        formant_variation=10,
        breathiness=10,
        warmth=42,
        brightness=48,
        tags=["latin", "motet", "renaissance", "polyphony"]
    ),
    create_preset(
        "Latin 3: Oratorio Solo",
        "Solo oratorio vocal style",
        "latin",
        "formant",
        "ah eh ee oh oo",
        num_voices=4,
        formant_mix=98,
        subharmonic_mix=2,
        stereo_width=50,
        vibrato_rate=6.2,
        vibrato_depth=24,
        reverb_mix=35,
        reverb_size=60,
        attack=55,
        release=220,
        breathiness=8,
        warmth=48,
        brightness=52,
        tags=["latin", "oratorio", "solo", "classical"]
    ),

    # KLINGON (3 presets) - Fake/constructed language
    create_preset(
        "Klingon 1: Battle Chant",
        "Warrior's battle chant",
        "klingon",
        "subharmonic",
        "ghgh vadh vadh ghgh",
        num_voices=16,
        formant_mix=30,
        subharmonic_mix=70,
        stereo_width=90,
        vibrato_rate=4.0,
        vibrato_depth=40,
        reverb_mix=25,
        reverb_size=45,
        attack=40,
        release=200,
        pitch_variation=8,
        timing_variation=4,
        breathiness=12,
        warmth=50,
        brightness=40,
        tags=["klingon", "battle", "chant", "warrior", "subharmonic"]
    ),
    create_preset(
        "Klingon 2: Opera Solo",
        "Klingon opera solo voice",
        "klingon",
        "formant",
        "qlIj vadh ghgh",
        num_voices=4,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=60,
        vibrato_rate=7.5,
        vibrato_depth=38,
        reverb_mix=20,
        reverb_size=35,
        attack=35,
        release=180,
        breathiness=6,
        warmth=40,
        brightness=65,
        tags=["klingon", "opera", "solo", "dramatic"]
    ),
    create_preset(
        "Klingon 3: Council Chamber",
        "High Council deliberation voices",
        "klingon",
        "diphone",
        "ghgh-qlIj vadh-ghgh",
        num_voices=8,
        formant_mix=85,
        subharmonic_mix=15,
        stereo_width=70,
        vibrato_rate=5.0,
        vibrato_depth=22,
        reverb_mix=30,
        reverb_size=55,
        attack=50,
        release=220,
        pitch_variation=10,
        timing_variation=5,
        breathiness=10,
        warmth=45,
        brightness=50,
        tags=["klingon", "council", "chamber", "deliberation"]
    ),

    # THROAT SINGING (3 presets) - Fake/specialized technique
    create_preset(
        "Throat Singing 1: Kargyraa",
        "Deep kargyraa style from Tuva",
        "throat_singing",
        "subharmonic",
        "oh oh oh",
        num_voices=4,
        formant_mix=15,
        subharmonic_mix=85,
        stereo_width=60,
        vibrato_rate=2.5,
        vibrato_depth=50,
        reverb_mix=15,
        reverb_size=30,
        attack=120,
        release=450,
        pitch_variation=4,
        timing_variation=2,
        formant_variation=10,
        breathiness=8,
        warmth=65,
        brightness=20,
        tags=["throat-singing", "kargyraa", "tuvan", "deep", "subharmonic"]
    ),
    create_preset(
        "Throat Singing 2: Sygyt",
        "Bright sygyt whistle style",
        "throat_singing",
        "subharmonic",
        "oh oh oh oh",
        num_voices=6,
        formant_mix=25,
        subharmonic_mix=75,
        stereo_width=70,
        vibrato_rate=3.5,
        vibrato_depth=45,
        reverb_mix=20,
        reverb_size=40,
        attack=100,
        release=400,
        pitch_variation=6,
        timing_variation=3,
        formant_variation=12,
        breathiness=5,
        warmth=50,
        brightness=55,
        tags=["throat-singing", "sygyt", "whistle", "bright"]
    ),
    create_preset(
        "Throat Singing 3: Borbangnadyr",
        "Pulsating borbangnadyr style",
        "throat_singing",
        "subharmonic",
        "oh oh oh",
        num_voices=8,
        formant_mix=20,
        subharmonic_mix=80,
        stereo_width=80,
        vibrato_rate=5.0,
        vibrato_depth=55,
        reverb_mix=25,
        reverb_size=50,
        attack=90,
        release=350,
        pitch_variation=7,
        timing_variation=4,
        formant_variation=15,
        breathiness=10,
        warmth=55,
        brightness=35,
        tags=["throat-singing", "borbangnadyr", "pulsating", "rhythmic"]
    ),

    # JAPANESE (3 presets) - Real language
    create_preset(
        "Japanese 1: Noh Theater",
        "Traditional Noh chanting style",
        "japanese",
        "formant",
        "ah ee ih oh",
        num_voices=4,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=50,
        vibrato_rate=4.5,
        vibrato_depth=15,
        reverb_mix=35,
        reverb_size=60,
        attack=80,
        release=300,
        pitch_variation=5,
        timing_variation=3,
        breathiness=18,
        warmth=55,
        brightness=40,
        tags=["japanese", "noh", "theater", "traditional"]
    ),
    create_preset(
        "Japanese 2: Pop Group",
        "Modern J-pop vocal group",
        "japanese",
        "diphone",
        "ah-eh ee-oh",
        num_voices=6,
        formant_mix=92,
        subharmonic_mix=8,
        stereo_width=75,
        vibrato_rate=6.8,
        vibrato_depth=30,
        reverb_mix=18,
        reverb_size=38,
        attack=25,
        release=160,
        breathiness=8,
        warmth=30,
        brightness=70,
        tags=["japanese", "j-pop", "modern", "group"]
    ),
    create_preset(
        "Japanese 3: Buddhist Chant",
        "Zen Buddhist sutra chanting",
        "japanese",
        "formant",
        "ah eh ee oh oo",
        num_voices=12,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=65,
        vibrato_rate=3.8,
        vibrato_depth=12,
        reverb_mix=40,
        reverb_size=70,
        attack=100,
        release=400,
        pitch_variation=6,
        timing_variation=4,
        breathiness=15,
        warmth=60,
        brightness=35,
        tags=["japanese", "buddhist", "zen", "chant", "meditation"]
    ),

    # CHINESE (3 presets) - Real language
    create_preset(
        "Chinese 1: Beijing Opera",
        "Traditional Beijing opera style",
        "chinese",
        "formant",
        "ah ee ih oh",
        num_voices=6,
        formant_mix=98,
        subharmonic_mix=2,
        stereo_width=55,
        vibrato_rate=8.0,
        vibrato_depth=35,
        reverb_mix=20,
        reverb_size=35,
        attack=30,
        release=180,
        pitch_variation=8,
        timing_variation=4,
        breathiness=10,
        warmth=40,
        brightness=75,
        tags=["chinese", "beijing-opera", "traditional", "dramatic"]
    ),
    create_preset(
        "Chinese 2: Folk Choir",
        "Chinese folk singing ensemble",
        "chinese",
        "diphone",
        "ah-eh ee-oh oh-oo",
        num_voices=16,
        formant_mix=95,
        subharmonic_mix=5,
        stereo_width=80,
        vibrato_rate=5.5,
        vibrato_depth=22,
        reverb_mix=25,
        reverb_size=45,
        attack=45,
        release=200,
        pitch_variation=12,
        timing_variation=6,
        breathiness=12,
        warmth=50,
        brightness=55,
        tags=["chinese", "folk", "ensemble", "traditional"]
    ),
    create_preset(
        "Chinese 3: Temple Chant",
        "Taoist temple chanting",
        "chinese",
        "formant",
        "ah eh ee oh oo",
        num_voices=8,
        formant_mix=100,
        subharmonic_mix=0,
        stereo_width=60,
        vibrato_rate=4.2,
        vibrato_depth=14,
        reverb_mix=38,
        reverb_size=65,
        attack=90,
        release=350,
        pitch_variation=5,
        timing_variation=3,
        breathiness=14,
        warmth=58,
        brightness=42,
        tags=["chinese", "taoist", "temple", "chant", "meditation"]
    ),
]

def main():
    preset_dir = "/Users/bretbouchard/apps/schill/choir-v2-universal/presets/factory"

    print("Generating Choir V2.0 Factory Presets...")
    print("=" * 60)

    # Generate all presets
    all_presets = (
        schillinger_presets +
        classical_presets +
        original_presets +
        language_presets
    )

    for preset in all_presets:
        save_preset(preset, preset_dir)

    print("=" * 60)
    print(f"\n✓ Generated {len(all_presets)} factory presets successfully!")
    print(f"  - Schillinger Songs: {len(schillinger_presets)}")
    print(f"  - Classical Music: {len(classical_presets)}")
    print(f"  - Original Compositions: {len(original_presets)}")
    print(f"  - Language Showcase: {len(language_presets)}")
    print(f"\nLocation: {preset_dir}")

if __name__ == "__main__":
    main()
